name: Deploy

on:
  push:
    branches:
      - Testing

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: 547dea58-153f-4150-b8d8-d0eb43082a2c
          heroku_app_name: "munchysite" #Must be unique in Heroku
          heroku_email: "munchyjunk6@outlook.com"
